version: "3"

services: 
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: Test
    ports:
      - "27017:27017"
  
  app:
    build: .
    image: dekamik/dvbcrud.mongodb.api.testapi:latest
    restart: always
    ports:
      - "3000:80"
      - "3001:443"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: admin
      DB_SERVER: localhost
      DB_DBNAME: Test
    depends_on: 
      - db