language: csharp

mono: none

dotnet: 3.1

install: dotnet restore

before_script: dotnet test

script: dotnet build DvBCrud.MongoDB.Api/DvBCrud.MongoDB.Api.csproj # Builds DvBCrud.MongoDB aswell (as a dependency)

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh ${TRAVIS_TAG} ${NUGET_API_KEY} ${NUGET_SOURCE}
  on:
    tags: true
