version: "3"

services: 
  db:
    container_name: dvbcrud.db
    hostname: dvbcrud.db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
  
  app:
    container_name: dvbcrud.api
    hostname: dvbcrud.api
    build: 
      context: .
      dockerfile: "./DvBCrud.MongoDb.Api.TestApi/Dockerfile"
    image: dekamik/dvbcrud.mongodb.api.testapi:latest
    restart: always
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION_STRING: "mongodb://root:root@dvbcrud.db:27017/admin?retryWrites=true&w=majority"
    depends_on: 
      - db