name: Unit tests
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
